import { Child, Children, Component, Ref, Elements, HEvent, HMouseEvent, HChangeEvent } from "./types";
declare const createElement: <E extends "object" | "a" | "abbr" | "address" | "applet" | "area" | "article" | "aside" | "audio" | "b" | "base" | "basefont" | "bdi" | "bdo" | "blockquote" | "body" | "br" | "button" | "canvas" | "caption" | "cite" | "code" | "col" | "colgroup" | "data" | "datalist" | "dd" | "del" | "details" | "dfn" | "dialog" | "dir" | "div" | "dl" | "dt" | "em" | "embed" | "fieldset" | "figcaption" | "figure" | "font" | "footer" | "form" | "frame" | "frameset" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "head" | "header" | "hgroup" | "hr" | "html" | "i" | "iframe" | "img" | "input" | "ins" | "kbd" | "label" | "legend" | "li" | "link" | "main" | "map" | "mark" | "marquee" | "menu" | "meta" | "meter" | "nav" | "noscript" | "ol" | "optgroup" | "option" | "output" | "p" | "param" | "picture" | "pre" | "progress" | "q" | "rp" | "rt" | "ruby" | "s" | "samp" | "script" | "section" | "select" | "slot" | "small" | "source" | "span" | "strong" | "style" | "sub" | "summary" | "sup" | "table" | "tbody" | "td" | "template" | "textarea" | "tfoot" | "th" | "thead" | "time" | "title" | "tr" | "track" | "u" | "ul" | "var" | "video" | "wbr", C extends Component<{}>>(name: E | C, props: Elements[E] | Parameters<C>[0], ...children: Child[]) => HTMLElement;
declare const render: (element: HTMLElement, parent: HTMLElement) => void;
declare const setStyles: <T extends HTMLElement>(ref: Ref<T>, styles: Partial<CSSStyleDeclaration>) => void;
declare const append: <T extends HTMLElement>(ref: Ref<T>, children: Children) => void;
declare const remove: <T extends HTMLElement>(ref: Ref<T>) => void;
declare const replaceContent: <T extends HTMLElement>(ref: Ref<T>, children: Children) => void;
declare const createRef: <T = null>() => Ref<T>;
export * from "./types";
export declare type MouseEvent<T> = HMouseEvent<T>;
export declare type EventChange<T> = HChangeEvent<T>;
export declare type Event<T> = HEvent<T>;
export { render, replaceContent, remove, setStyles, createElement, createRef, append };
